name: Jekyll Gallery Generator
markdown: redcarpet
pygments: true

permalink: none

exclude:
  - Gemfile
  - Gemfile.lock
  - bower.json
  - bower_components
  - package.json
  - node_modules
  - lib
  - '*.gem'
  - '*.gemspec'

gallery: 
  src: 
    basepath: _galleries/_fullsizes
  dst: 
    basepath: _galleries/_generated
    baseurl: /img/galleries
  quality: 85
  presets: 
    thumb: 
      width: 450
    large_phones: 
      width: 650
    large_pads: 
      width: 1024
    large: 
      width: 1400
  opts: 
    min_col_width: 
      desktop: 320
      pad: 320
      phone: 300
    gutter_width: 3
    chunk_size: 8
    first_chunk: 15
